[tools]
go = "1.23.1"

[settings]
activate_aggressive = true
color = false
experimental = true

[settings.status]
missing_tools = "always"
show_env = true
show_tools = true

[env]
ROOT = "{{config_root}}"
