name = "Scratch"
version = "0.0.1"
description = "Some scratch ideas and documentation for riconto"
license = ["CC0"]

[[files]]
name = "Scratch Ideas"
output = "./dist/scratch"
path = "./src/scratch/main.md"

[[files]]
name = "Documentation"
output = "./dist/riconto"
path = "./src/documentation/main.md"

[[authors]]
name = "carddamom"
email = "carddamom@tutanota.com"
